### ISSUE TITLE
Cant add api and other entries more than one.

### ISSUE THREAD

**Issue by sylentears** [muhammad-shariq/exclusiveunlock#3]
Many restriction are there. cant change admin email but password and name.
cant add more api's more than 1
cant add brands more than 1,
even every option cant add more than one.

added api does not shows services list in panel to select and show in our panel.

**Comment by sylentears** [comment]
record added message successful, but not display,

**Comment by muhammad-shariq** [comment]
Hello, 
I had added change admin email address restriction due to some security reasons but you can change that from database table very easily I can help in that regard.

As far as other restriction, There is no restrictions from my side there must be some installation issue. There are multiple sites running on my software.

Please send me your Skype ID on my email address: shariq2k@yahoo.com so I can look into it.

Thanks.

**Comment by sylentears** [comment]
Hello Muhammad,


Thank you very much for your quick response, i do appreciate your work and support. can we talk on whatsapp (923027691227) because i dont use skype because its very heavy now and syatem and mobile goes slow.


Today i added services according to you advise, Thanks again,


i added another API, but another except the 1st api does not shows in api manager,


Please send me your whatsapp no to share with you details and discuss further to enhance your work.


Regards:
Muhammad Shahbaz
923027691227
971503306703
________________________________

**Comment by muhammad-shariq** [comment]
Okay, I will send you a msg on WhatsApp.

**Comment by imanthaashan77** [comment]
> Many restriction are there. cant change admin email but password and name.
> cant add more api's more than 1
> cant add brands more than 1,
> even every option cant add more than one.
> 
> added api does not shows services list in panel to select and show in our panel.


hello sir , if you are success
can you help me .............    write my whatsapp number    +94712556303   https://wa.me/94712556303

github exclusive web
